export type FicheTemplate = {
  id: string
  i18nKey: string
  defaultTitle: string
  defaultData: Record<string, any>
}

export const FICHE_TEMPLATES: Record<string, FicheTemplate> = {
  asso_fr: {
    id: "asso_fr",
    i18nKey: "asso_fr",
    defaultTitle: "Fiche projet associatif",
    defaultData: {
      ficheTitle: "",
      thematic: "",
      thematicOther: "",
      association: "",
      referent: "",
      phone: "",
      email: "",
      logoUrl: "",
      partnerLogoUrl: "",
      context: "",
      origin: "",
      linkToProject: "",
      audience: "",
      ageProfile: "",
      estimatedParticipants: "",
      geographicArea: "",
      needs: {
        isolation: false,
        economic: false,
        culturalAccess: false,
        educational: false,
        other: false,
      },
      needsOther: "",
      generalObjective: "",
      specificObjectives: ["", "", "", ""],
      actionTypes: {
        workshops: false,
        event: false,
        individualSupport: false,
        awareness: false,
        other: false,
      },
      actionTypesOther: "",
      actions: [
        { description: "", audience: "", frequency: "", period: "" },
        { description: "", audience: "", frequency: "", period: "" },
      ],
      volunteers: "",
      employees: "",
      externalContributors: "",
      materialResources: "",
      partners: {
        localGov: false,
        associations: false,
        schools: false,
        companies: false,
        other: false,
      },
      partnersOther: "",
      targetParticipants: "",
      targetAttendance: "",
      qualitativeIndicators: "",
      trackingTools: {
        attendance: false,
        satisfaction: false,
        collective: false,
        report: false,
        other: false,
      },
      trackingToolsOther: "",
      perspectives: "",
      date: "",
      referentSignature: "",
      boardOpinion: "",
      observations: "",
    },
  },
  blank: {
    id: "blank",
    i18nKey: "blank",
    defaultTitle: "Sheet",
    defaultData: { content: "" },
  },
  recu_don: {
    id: "recu_don",
    i18nKey: "recu_don",
    defaultTitle: "Reçu fiscal de dons",
    defaultData: {
      receiptNumber: "",
      orgName: "",
      orgAddress: "",
      orgObject: "",
      orgCategory: "œuvre ou organisme d'intérêt général",
      regime: { art200: true, art238bis: false, art978: false },
      donorCivility: "",
      donorName: "",
      donorAddress: "",
      amount: 0,
      donDate: "",
      forme: "don_manuel",
      nature: "numeraire",
      modeVersement: "virement",
      abandonRevenus: false,
      fraisBenevoles: false,
      signatoryName: "",
      signatoryQuality: "Président(e)",
      signatureCity: "",
      signatureDate: "",
    },
  },
  budget_equilibre: {
    id: "budget_equilibre",
    i18nKey: "budget_equilibre",
    defaultTitle: "Budget prévisionnel à l'équilibre",
    defaultData: {
      association: "",
      scope: "Budget prévisionnel annuel",
      year: String(new Date().getFullYear()),
      charges: [
        { label: "60 — Achats (matières, fournitures)", amount: 0 },
        { label: "61 — Services extérieurs (locations, assurances)", amount: 0 },
        { label: "62 — Autres services extérieurs (honoraires, communication)", amount: 0 },
        { label: "63 — Impôts et taxes", amount: 0 },
        { label: "64 — Charges de personnel", amount: 0 },
        { label: "65 — Autres charges de gestion courante", amount: 0 },
      ],
      produits: [
        { label: "70 — Ventes / prestations", amount: 0 },
        { label: "74 — Subventions d'exploitation", amount: 0 },
        { label: "75 — Cotisations, dons et legs", amount: 0 },
        { label: "76 — Produits financiers", amount: 0 },
      ],
      notes: "",
    },
  },
}
