export type FicheTemplate = {
  id: string
  i18nKey: string
  defaultTitle: string
  defaultData: Record<string, any>
}

export const FICHE_TEMPLATES: Record<string, FicheTemplate> = {
  asso_fr: {
    id: "asso_fr",
    i18nKey: "asso_fr",
    defaultTitle: "Fiche projet associatif",
    defaultData: {
      ficheTitle: "",
      thematic: "",
      thematicOther: "",
      association: "",
      referent: "",
      phone: "",
      email: "",
      logoUrl: "",
      partnerLogoUrl: "",
      context: "",
      origin: "",
      linkToProject: "",
      audience: "",
      ageProfile: "",
      estimatedParticipants: "",
      geographicArea: "",
      needs: {
        isolation: false,
        economic: false,
        culturalAccess: false,
        educational: false,
        other: false,
      },
      needsOther: "",
      generalObjective: "",
      specificObjectives: ["", "", "", ""],
      actionTypes: {
        workshops: false,
        event: false,
        individualSupport: false,
        awareness: false,
        other: false,
      },
      actionTypesOther: "",
      actions: [
        { description: "", audience: "", frequency: "", period: "" },
        { description: "", audience: "", frequency: "", period: "" },
      ],
      volunteers: "",
      employees: "",
      externalContributors: "",
      materialResources: "",
      partners: {
        localGov: false,
        associations: false,
        schools: false,
        companies: false,
        other: false,
      },
      partnersOther: "",
      targetParticipants: "",
      targetAttendance: "",
      qualitativeIndicators: "",
      trackingTools: {
        attendance: false,
        satisfaction: false,
        collective: false,
        report: false,
        other: false,
      },
      trackingToolsOther: "",
      perspectives: "",
      date: "",
      referentSignature: "",
      boardOpinion: "",
      observations: "",
    },
  },
  blank: {
    id: "blank",
    i18nKey: "blank",
    defaultTitle: "Sheet",
    defaultData: { content: "" },
  },
  recu_don: {
    id: "recu_don",
    i18nKey: "recu_don",
    defaultTitle: "Reçu fiscal de dons",
    defaultData: {
      receiptNumber: "",
      orgName: "",
      orgAddress: "",
      orgObject: "",
      orgCategory: "œuvre ou organisme d'intérêt général",
      regime: { art200: true, art238bis: false, art978: false },
      donorCivility: "",
      donorName: "",
      donorAddress: "",
      amount: 0,
      donDate: "",
      forme: "don_manuel",
      nature: "numeraire",
      modeVersement: "virement",
      abandonRevenus: false,
      fraisBenevoles: false,
      signatoryName: "",
      signatoryQuality: "Président(e)",
      signatureCity: "",
      signatureDate: "",
    },
  },
  budget_equilibre: {
    id: "budget_equilibre",
    i18nKey: "budget_equilibre",
    defaultTitle: "Budget prévisionnel à l'équilibre",
    defaultData: {
      association: "",
      scope: "Budget prévisionnel annuel",
      year: String(new Date().getFullYear()),
      charges: [
        { label: "60 — Achats (matières, fournitures)", amount: 0 },
        { label: "61 — Services extérieurs (locations, assurances)", amount: 0 },
        { label: "62 — Autres services extérieurs (honoraires, communication)", amount: 0 },
        { label: "63 — Impôts et taxes", amount: 0 },
        { label: "64 — Charges de personnel", amount: 0 },
        { label: "65 — Autres charges de gestion courante", amount: 0 },
      ],
      produits: [
        { label: "70 — Ventes / prestations", amount: 0 },
        { label: "74 — Subventions d'exploitation", amount: 0 },
        { label: "75 — Cotisations, dons et legs", amount: 0 },
        { label: "76 — Produits financiers", amount: 0 },
      ],
      notes: "",
    },
  },
  demande_subvention: {
    id: "demande_subvention",
    i18nKey: "demande_subvention",
    defaultTitle: "Demande de subvention (CERFA 12156)",
    defaultData: {
      fundingBody: "", requestType: "projet", amountRequested: 0, year: String(new Date().getFullYear()),
      legalName: "", rna: "", siret: "", address: "", postalCode: "", city: "",
      email: "", phone: "", website: "", representativeName: "", representativeRole: "Président(e)",
      agrements: "", rupRecognized: false, fiscalRegime: "Non assujettie aux impôts commerciaux", aidesPubliques3ans: "",
      volunteers: "", employees: "", etp: "", members: "",
      budgetYear: String(new Date().getFullYear()),
      charges: [
        { label: "60 — Achats", amount: 0 },
        { label: "61 — Services extérieurs", amount: 0 },
        { label: "62 — Autres services extérieurs", amount: 0 },
        { label: "64 — Charges de personnel", amount: 0 },
      ],
      produits: [
        { label: "70 — Ventes / prestations", amount: 0 },
        { label: "74 — Subventions d'exploitation", amount: 0 },
        { label: "75 — Cotisations, dons", amount: 0 },
      ],
      projectTitle: "", objectives: "", description: "", beneficiaries: "", territory: "",
      calendar: "", means: "", evaluation: "",
      attestation: true, cerSigned: true,
      signatureCity: "", signatureDate: "", signatoryName: "", signatoryRole: "Président(e)",
    },
  },
  convention_subvention: {
    id: "convention_subvention",
    i18nKey: "convention_subvention",
    defaultTitle: "Convention de subvention",
    defaultData: {
      reference: "",
      financeur: "", financeurRep: "", financeurRole: "", financeurAddress: "",
      legalName: "", representativeName: "", representativeRole: "Président(e)", rna: "", siret: "", address: "",
      objet: "", amount: 0, exercice: String(new Date().getFullYear()),
      paymentTerms: "La subvention est versée en une seule fois à la signature de la présente convention, par virement sur le compte bancaire du bénéficiaire.",
      duration: "La présente convention est conclue pour l'exercice en cours. Elle prend effet à sa signature.",
      affectation: "",
      signatureCity: "", signatureDate: "",
    },
  },
  rapport_activite: {
    id: "rapport_activite",
    i18nKey: "rapport_activite",
    defaultTitle: "Rapport annuel d'activité",
    defaultData: {
      legalName: "", year: String(new Date().getFullYear() - 1),
      presidentWord: "", governance: "", members: "", volunteers: "", employees: "",
      activities: [{ title: "", description: "", beneficiaries: "", period: "" }],
      results: "", financialSummary: "", perspectives: "",
      signatureCity: "", signatureDate: "", signatoryName: "", signatoryRole: "Président(e)",
    },
  },
  attestation_honneur: {
    id: "attestation_honneur",
    i18nKey: "attestation_honneur",
    defaultTitle: "Attestation sur l'honneur",
    defaultData: {
      legalName: "", rna: "", siret: "", address: "",
      representativeName: "", representativeRole: "Président(e)",
      fundingBody: "", amountRequested: 0,
      decExact: true, decObligations: true, decCer: true, decNoDistribution: true, decRegular: true,
      signatureCity: "", signatureDate: "",
    },
  },
}
